server:
  port: 8087

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-client-test
    api-b:
      path: /api-b/**
      serviceId: eureka-client-test2
